services:
  - docker

env:
  - distro=alpine
  - distro=debian
  - distro=ubuntu
  - distro=fedora
  - distro=centos
  #- distro=archlinux


before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 379CE192D401AB61
  - echo "deb https://dl.bintray.com/nxadm/rakudo-pkg-debs `lsb_release -cs` main" | sudo tee -a /etc/apt/sources.list.d/rakudo-pkg.list 
  - sudo apt-get update && sudo apt-get install rakudo-pkg

install:
  - PATH=/usr/local/bin:/opt/rakudo-pkg/bin/:/home/travis/.perl6/bin:$PATH && zef install --/test https://github.com/melezhik/Sparrow6.git
  - PATH=/usr/local/bin:/opt/rakudo-pkg/bin/:/home/travis/.perl6/bin:$PATH && zef install --/test .

script:
  - sh ./.travis.d/docker-run.sh "$distro"
  - sh ./.travis.d/bootstrap.sh "$distro"
  - sh ./.travis.d/post-configure.sh "$distro"
  - sh ./.travis.d/run.sh "$distro"

