language: "perl"

services:
  - docker

env:
  - TEST=prove
  - TEST=bootstrap:alpine
  - TEST=bootstrap:amazon
  - TEST=bootstrap:archlinux
  - TEST=bootstrap:centos
  - TEST=bootstrap:debian
  - TEST=bootstrap:fedora
  - TEST=bootstrap:funtoo
  - TEST=bootstrap:ubuntu
  - TEST=api:asserts
  - TEST=api:asserts-http-ok
  - TEST=api:bash
  - TEST=api:copy-local-file
  - TEST=api:cpan
  - TEST=api:directory
  - TEST=api:files
  - TEST=api:git
  - TEST=api:group
  - TEST=api:hostname
  - TEST=api:packages
  - TEST=api:read-config
  - TEST=api:scp
  - TEST=api:service
  - TEST=api:ssh
  - TEST=api:systemd
  - TEST=api:task_run_short
  - TEST=api:templates
  - TEST=api:user
  - TEST=api:zef
    
install:
  - cpanm https://github.com/melezhik/outthentic.git
  - cpanm https://github.com/melezhik/sparrow.git
  - sparrow index update
  - sparrow plg install rakudo-install
  - sparrow plg run rakudo-install --param user_install=on --param sudo=on --param url=https://github.com/nxadm/rakudo-pkg/releases/download/2017.09.1%2B2/perl6-rakudo-moarvm-debian8.7_20170900-01_amd64.deb
  - export PATH=$PATH:$HOME/.perl6/bin:/opt/rakudo/bin
  - zef install .

script:
  - sh ./.travis.d/run.sh "$TEST"
