env:
  global:
    - PATH=/usr/local/bin:/opt/rakudo-pkg/bin/:/home/travis/.perl6/bin:$PATH
    - SP6_REPO=https://sparrowhub.org

before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 379CE192D401AB61
  - echo "deb https://dl.bintray.com/nxadm/rakudo-pkg-debs `lsb_release -cs` main" | sudo tee -a /etc/apt/sources.list.d/rakudo-pkg.list 
  - sudo apt-get update && sudo apt-get install rakudo-pkg

install:
  - zef install --/test https://github.com/melezhik/Sparrow6.git
  - zef install --/test .
  - docker pull jjmerelo/alpine-perl6
  - docker run --name alpine -td --entrypoint sh  jjmerelo/alpine-perl6

script:
  - sparrowdo --docker=alpine --verbose --bootstrap

