language: "perl"

services:
  - docker

env:
  - PATH=.ducky/:/opt/rakudo/bin/:~/.perl6/bin:$PATH
  - TEST_TARGET=alpine
  - TEST_TARGET=amazon
  - TEST_TARGET=archlinux
  - TEST_TARGET=debian
  - TEST_TARGET=fedora
  - TEST_TARGET=funtoo
  - TEST_TARGET=ubuntu

before_install:
  - docker run --privileged -d --name centos7 --entrypoint  init -v $PWD:/var/ducky -v /sys/fs/cgroup:/sys/fs/cgroup:ro centos
  - docker run -t -d --name "$TEST_TARGET" "$TEST_TARGET" bash
  - docker images
  - docker ps

install:
  - cpanm https://github.com/melezhik/sparrow.git
  - sparrow index update
  - sparrow plg install rakudo-install
  - sparrow plg run rakudo-install --param user_install=on --param sudo=on --param url=https://github.com/nxadm/rakudo-pkg/releases/download/2017.09.1%2B2/perl6-rakudo-moarvm-debian8.7_20170900-01_amd64.deb
  - zef install .
  - git clone https://github.com/melezhik/ducky.git .ducky

script:
  - sparrowdo --docker="$TEST_TARGET" --no_sudo  --bootstrap  --task_run=bash@command=uptime
