env:
  global:
    - PATH=/usr/local/bin:/opt/rakudo-pkg/bin/:/home/travis/.perl6/bin:$PATH

before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 379CE192D401AB61
  - echo "deb https://dl.bintray.com/nxadm/rakudo-pkg-debs `lsb_release -cs` main" | sudo tee -a /etc/apt/sources.list.d/rakudo-pkg.list 
  - sudo apt-get update && sudo apt-get install rakudo-pkg

install:
  - zef install --/test https://github.com/melezhik/Sparrow6.git
  - zef install --/test .
  - docker run --name alpine -td --entrypoint sh  jjmerelo/alpine-perl6
  - docker run --name debian -td --entrypoint sh  debian
  - docker run --name ubuntu -td --entrypoint sh  ubuntu
  - docker run --name fedora -td --entrypoint sh  fedora
  - docker run --name centos -td --entrypoint sh  archlinux

script:
  - sparrowdo --docker=alpine --verbose --bootstrap
  - sparrowdo --docker=debian --verbose --bootstrap
  - sparrowdo --docker=ubuntu --verbose --bootstrap
  - sparrowdo --docker=fedora --verbose --bootstrap
  - sparrowdo --docker=centos --verbose --bootstrap
  - sparrowdo --docker=archlinux --verbose --bootstrap

