language: perl

env:
  global:
    - PATH=/usr/local/bin:/opt/rakudo-pkg/bin/:/home/travis/.perl6/bin:$PATH
    - SP6_REPO=https://sparrowhub.org

before_install:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 379CE192D401AB61
  - echo "deb https://dl.bintray.com/nxadm/rakudo-pkg-debs `lsb_release -cs` main" | sudo tee -a /etc/apt/sources.list.d/rakudo-pkg.list 
  - sudo apt-get update && sudo apt-get install rakudo-pkg
  - cpanm --test -q Carton

install:
  - cpanm --notest -q JSON Template
  - zef install --/test .
  - docker pull jjmerelo/alpine-perl6

script:
  - docker run -v `pwd`:/app -it  jjmerelo/alpine-perl6 /app/test.sh

