language: perl

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y cpanminus
  - sudo cpanm -q --notest install Sparrow
  - cat /dev/zero | ssh-keygen -q -N ""
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - chmod og-wx ~/.ssh/authorized_keys

install:
    - export PATH=/opt/rakudo/bin:~/.perl6/bin:$PATH
    - wget https://github.com/nxadm/rakudo-pkg/releases/download/2017.03_02/perl6-rakudo-moarvm-ubuntu16.04_20170300-02_amd64.deb
    - sudo dpkg -i *.deb
    - install_zef_as_user.sh
    - zef install .
    - zef install Sparrowdo::Sparrow::Update
script:
  - sparrowdo --module_run=Sparrow::Update --bootstrap --host=127.0.0.1
  - sparrowdo --task_run=df-check --host=127.0.0.1
  - strun --root examples/
